version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: matrix-postgres
    environment:
      POSTGRES_DB: synapse_db
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      TZ: "Asia/Kolkata"
    command: postgres -c timezone=Asia/Kolkata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user -d synapse_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/data
    ports:
      - "8008:8008"
    restart: unless-stopped

  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    ports:
      - "8080:80"
    restart: unless-stopped
